name: Pull Request Pipeline

on:
  pull_request:
    branches:
      - main  # Trigger the pipeline for PRs targeting the `main` branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt  # Flask uses `dev.txt` for development dependencies

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest  # Assuming Flask uses pytest for testing (common in Flask apps)

